### ISSUE TITLE
How do we handle nixos releases in future?

### ISSUE THREAD

**Issue by Mic92** [numtide/srvos#11]
Just now we only target nixos-unstable. I am leaning into having release branches to avoid having to put conditionals in the code whenever module options changes.

**Comment by zimbatm** [comment]
Same. It depends on what is the most practical.

**Comment by zimbatm** [comment]
By the way, flakes using srvos should probably follow `srvos.inputs.nixpkgs`

**Comment by zimbatm** [comment]
Maybe we should also run the NixOS VM tests

**Comment by Mic92** [comment]
> By the way, flakes using srvos should probably follow `srvos.inputs.nixpkgs`

Not quite sure what you mean with that.

**Comment by zimbatm** [comment]
```
{
  inputs.srvos.url = "github:numtide/srvos";
  // somehow follow the nixpkgs version pinned by srvos
  inputs.nixpkgs.follows = "srvos.nixpkgs";
}
```

**Comment by Mic92** [comment]
You would rather need access nixpkgs like that `srvos.inputs.nixpkgs` in your flake. I don't think there is a reverse `.follows`. However I often see myself in the position where I have to temporary or permanent fork nixpkgs in order to use certain fixes and changes so it might be not practically to require this.

**Comment by zimbatm** [comment]
Maybe the srvos flake could be exposed as a fake nixpkgs, like we do in nixpkgs-unfree.
```
inputs.nixpkgs.url = "github:numtide/srvos";
```

**Comment by Mic92** [comment]
Seems a bit hacky. For nixpkgs-unfree this is fine but fore srvos it would be more transparent to use `srvos.inputs.nixpkgs`. Otherwise the code would need a comment or it looks like a bug.

**Comment by Kiskae** [comment]
Just a heads up that per https://github.com/numtide/srvos/commit/52fb159b7da3082859cba5faf65f4594947a96d7 the modules are no longer compatible with the `nixos-23.05` channel.

**Comment by Mic92** [comment]
I think I actually care now about 23.05 compatibility.

**Comment by Mic92** [comment]
https://github.com/numtide/srvos/pull/191

**Comment by zimbatm** [comment]
Same. It's time to have CI test against both channels.

**Comment by Mic92** [comment]
Based on my experience with nixos hardware, it's usually not so hard to support two channels for small code bases. It makes it easier for us since we don't need to backport and easier for the user because they don't have to pick the right branch.
