### ISSUE TITLE
networking.useDHCP

### ISSUE THREAD

**Issue by boozedog** [numtide/srvos#131]
**Describe the bug**

I'm using DHCP on a cloud provider and srvos seems to not like it:

```
error: The option `networking.useDHCP' has conflicting definition values:
       - In `/nix/store/b04ysr6cypqgwhrz5180l9q26skj2nq2-source/nixos/common/networking.nix': false
       - In `/nix/store/jb02bxn7gpplmjcilj7cv120m0rxh1bm-source/hosts/ovh/hardware-configuration.nix': true
```

If I remove the `networking.useDHCP = true` then the network interface doesn't get an IP.

**Comment by otavio** [comment]
You need to assign it to the interface, not set it globally.

**Comment by boozedog** [comment]
Thanks @otavio I did try that: `networking.interfaces.ens3.useDHCP = lib.mkDefault true;`

Didn't seem to work. I can troubleshoot further now that I have a machine with a working console.

**Comment by otavio** [comment]
Check if the interface name is correct.

**Comment by boozedog** [comment]
Thanks @otavio you were right! Now I have a different problem but networking is fine :+1:
