### ISSUE TITLE
Networking setup between hetzner-online and hetzner-cloud should be the same

### ISSUE THREAD

**Issue by surfaceflinger** [numtide/srvos#280]
**Is your feature request related to a problem? Please describe.**

Hi,

why isn't `/nixos/hardware/hetzner-online/default.nix` exposed in nixosModules or imported by `/nixos/hardware/hetzner-cloud/default.nix`?

In particular - I have no idea how baremetal works on Hetzner, but the way of setting up IPv6 should be exactly the same between cloud and online. Perhaps these two should have some shared networking module?

**Comment by Mic92** [comment]
They are very different actually and do not really share common functionality. With hetzner-cloud ipv6 addresses are set automatically by using cloud-init while for in hetzner online, one has to manually set those.

**Comment by surfaceflinger** [comment]
Just checked again and it indeed works! Looks like I fricked something up last time I tried this 😕
