### ISSUE TITLE
[Hetzner Cloud] Networking does not work together with cloud-init

### ISSUE THREAD

**Issue by shyim** [numtide/srvos#96]
**Is your feature request related to a problem? Please describe.**

Cloud-Init together with the networking here does not work as cloud-init generates a network configuration which will be loaded first.

Solution is to delete `/etc/systemd/network/10-cloud-init-enp1s0.network` and then restart networking then the NixOS configuration works

**Comment by zimbatm** [comment]
There is a deeper issue where `cloud-init` doesn't have access to `dhclient` (which is deprecated), preventing it from standing up the interface and even querying the metadata service. If that was fixed, we could remove all of the networking code and the requirement to copy-paste the IPv6 address as well as it would come from that metadata server.

**Comment by shyim** [comment]
Ahhh. For now I did 
```
systemd.services.systemd-networkd.serviceConfig.ExecStartPre="${pkgs.coreutils-full}/bin/rm -f /etc/systemd/network/10-cloud-init-enp1s0.network";
```

😅

**Comment by zimbatm** [comment]
See https://github.com/NixOS/nixpkgs/issues/215571

**Comment by zimbatm** [comment]
fixed!
